### PR TITLE
create intermediate CA certificates + bug fixes

### LINKED ISSUE #2: easypki doesn't allow you to create intermediate CAs
Hey there,

I was looking to use `easypki` to create a CA that has the intent of becoming an offline root CA. When I went to begin creating intermediate certificates from the root CA, it became apparent that `easypki` lacked the ability to do so. At the same time, I noticed `easypki` also doesn't allow you to set the `MaxDepthLen`, which is something you may want on a root CA and probably on an intermediate.

I've preempted the `CONTRIBUTING.md` file, slightly, by making modifications to `easypki` to unblock myself. Because of there only being certain fields available in the `*x509.Certificate` struct, I believe this does require a breaking change in the API. It is mildly convenient because `GenerateCertifcate` is missing an `i` in certificate anyhow, so we can also fix that typo!

For the user, I've implemented the above as two flags:

* `--intermediate` - tells `easypki` to generate an intermediate
* `--max-depth-len` - sets the pathLenConstraint in the Basic Constrains standard extension

I'm happy to open a PR if you'd like to see the implementation or I am happy to discuss it more in this issue.

### LINKED ISSUE #3: easypki doesn't give server certs ExtKeyUsageClientAuth
While in the process of rolling out my CA I discovered an issue with the certificates being generated by `easypki`. I was trying to use certificates generated by `easypki` within Consul, but I kept getting errors indicating the certificate did not have the correct usage extensions. Upon inspection one of my organization's commercial certificates I noticed that it had both ServerAuth and ClientAuth.

I've fixed this bug in the same branch that adds the functionality requested in #2. If you'd like it separate from that I'd be happy to cherry-pick the work.

### LINKED ISSUE #4: easypki should add ExtKeyUsageAny extension for CAs
When troubleshooting certificate chain issues with the CA generated by `easypki` and Consul, I ran in to the following Hashicorp/Vault issue regarding an issue with CAs it was generating:

* https://github.com/hashicorp/vault/issues/846

In short, without the `ExtKeyUsageAny` extension the Go runtime was failing to validate the certificate chain. The suggested change by the Vault developers was to change Vault to give the CAs the `ExtKeyUsageAny` extension.

I've found/fixed this bug while working on my branch that implements the functionality in #2.

### PR DESCRIPTION
**Pull request by theckman**
**Note**: This change introduces breaking changes to the `easypki` API:

* The `GenerateCertificate` function had a typo in its name. It used to
  be `GenerateCertifcate` (missing an `i`).
* The `GenerateCertificate` function now takes a struct as a parameter,
  making it easier to use.

The main reason behind this change was to provide the ability to
generate intermediate CA certificates. This will allow people and
organizations to use `easypki` to create a multi-layered tree of trust.
In addition to that, the ability to set the maximum path length on CA
certificates was added to make the keys safer (less prone for abuse).

You can now generate intermediate certificates using the
`--intermediate` flag. This flag effectively creates a new CA
certificate, within the CA, but doesn't overwrite the `ca.crt` or
`ca.key` file. Instead, it uses the same logic as regular certificates
and saves the cert and key within the `issued/` and `private/`
directories respectively. It's suggested that the `--max-path-len` flag
be used when generating CA certificates.

You can now set the maximum path depth for a CA certificate by using the
`--max-path-len` flag. If you want to generate an offline root CA and
ensure that your intermediates cannot generate valid intermediate CA
certificates themselves, you would set `--max-path-len 1` when
generating the root CA. It's recommended to always use this flag when
generating CA certificates, otherwise that certificate will be valid for
an "infinite" number of intermediate certificates.

With the features above added, a few bugs were discovered in the
certificates being generated by `easypki`. Specifically we needed to fix
some issues with the KeyUsage and ExtKeyUsage settings of the certs.

While troubleshooting an issue with Consul, trying to do
verification of a TLS chain generated by `easypki`, I ran in to a
situation where the certificates were failing to validate. It turns out
there were a few issues that caused this to happen.

I found an issue on Hashicorp's Vault project referencing a similar
issue with CA certificates generated by Vault itself. This guided me to
the first bug that needed patching:

* https://github.com/hashicorp/vault/pull/852

>Assign ExtKeyUsageAny to CA certs to help with validation with the
>Windows Crypto API and Go's validation logic

The solution: when generating CAs, we now set the `ExtKeyUsage` to
`ExtKeyUsageAny`. This will mark the CA certificate as being valid for
any usage. Some X.509 validation systems require that all certificates
in the chain contain the requested usage, including in Go.

The second was that the server certificates weren't being assigned
`ExtKeyUsageClientAuth` causing issues with applications trying to use
the certificates as both client and server certificates. The fix is to
also give server certificates `ExtKeyUsageClientAuth`. Upon
investigation of certificates deployed for public Internet services, it
seems that `ExtKeyUsageClientAuth` is pretty common in server
certificates.

fixes #2
fixes #3
fixes #4

### CODE REVIEW

File: pkg/easypki/easyca.go [hunk 1]
```diff
@@ -66,22 +66,36 @@ func GeneratePrivateKey(path string) (*rsa.PrivateKey, error) {
 	return key, nil
 }
 
-func GenerateCertifcate(pkiroot, name string, template *x509.Certificate) error {
+// GenerationRequest is a struct for providing configuration to
+// GenerateCertifcate when actioning a certification generation request.
```
Comment (jeremy-clerc) [inline pkg/easypki/easyca.go]: Missing i to match the new everywhere.

**Comment by theckman** [comment]
@jeremy-clerc Nice find! I think I wrote that comment before I fixed the typo, so my editor helpfully completed the function name for me. Hah.

I've also made a change where I removed the `KeyUsageAny` change. I found that some things didn't like this being set, and was causing validation errors. By only setting the Client and Server usage we should be OK.

**Comment by fujin** [comment]
I confirm that they're :+1:  with these commits being contributed to google: I sent a pull request to @theckman with the above.

**Comment by fujin** [comment]
thanks, @jeremy-clerc!

**Comment by theckman** [comment]
@jeremy-clerc thank you for the quick turn-around on the issues and the code review. Much appreciated!
